services:
  nextjs:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./next:/app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
